info:
  description: Global file configuration

#Eureka configuration
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-service-v2.common.svc.cluster.local/eureka
  instance:
    preferIpAddress: true


#Spring Boot Admin & zipkin
spring:
  boot:
    admin:
      client:
        url: http://admin-service-v2.common.svc.cluster.local

#Actuactor configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
  endpoint:
    health:
      show-details: ALWAYS


#Oauth 2 auth endpoint

---

spring:
  profiles: default, native, unitTest, integrationTest

  boot:
    admin:
      client:
        url: http://localhost:7500

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    

---

spring:
  profiles: docker

  boot:
    admin:
      client:
        url: http://admin-service-v2:7500

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://eureka-service-v2:8761/eureka
  instance:
    preferIpAddress: false
