info:
  description: Global file configuration

#Eureka configuration
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-service-v2.common.svc.cluster.local/eureka
  instance:
    preferIpAddress: true


#Spring Boot Admin
spring:
  boot:
    admin:
      client:
        url: http://admin-service-v2.common.svc.cluster.local
        

#Actuactor configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
  endpoint:
    health:
      show-details: ALWAYS
      
#Feign CLients    
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic      


#Oauth 2 auth endpoint

---

spring:
  profiles: default, native, unitTest, integrationTest

  boot:
    admin:
      client:
        url: http://localhost:7500

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    
    

---

spring:
  profiles: docker

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-service-v2:8761/eureka
  instance:
    preferIpAddress: true
